### ISSUE TITLE
Can't build pdx237

### ISSUE THREAD

**Issue by m113e55ml** [sonyxperiadev/device-sony-pdx237#3] opened 2024-07-15 15:36 UTC
I'm trying to build android 14 r50 since days and followed every step on the official sony build guide for aosp.
But it keeps saying this':

`[100% 1/1] analyzing Android.bp files and generating ninja file at out/soong/bui
FAILED: out/soong/build.aosp_xqde54.ninja
cd "$(dirname "out/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename
 "out/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top 
"$TOP"     --soong_out "out/soong"     --out "out"     --soong_variables out/soo
ng/soong.aosp_xqde54.variables -o out/soong/build.aosp_xqde54.ninja --globListDi
r aosp_xqde54 --globFile out/soong/globs-aosp_xqde54.ninja -l out/.module_paths/
Android.bp.list --available_env out/soong/soong.environment.available --used_env
 out/soong/soong.environment.used.aosp_xqde54.build Android.bp
error: device/sony/common/hardware/health/Android.bp:1:1: "android.hardware.heal
th@2.0-service.sony" depends on undefined module "android.hardware.health@2.0-im
pl".
Or did you mean ["android.hardware.health@2.1-impl"]?
error: device/sony/common/hardware/health/Android.bp:1:1: "android.hardware.heal
th@2.0-service.sony" depends on undefined module "libhealthservice".
Or did you mean ["libartservice"]?
error: device/sony/common/hardware/health/Android.bp:1:1: "android.hardware.heal
th@2.0-service.sony" depends on undefined module "libhealthstoragedefault".
Or did you mean ["healthfitness-ui-statsd"]?
fatal errors encountered
21:09:35 soong bootstrap failed with: exit status 1

#### failed to build some targets (14 seconds) ####`

Also another problem is, when I run 
`source build/envsetup.sh && lunch
`

There is no device as option to pick.
I have to invoke lunch by entering:
export xqde54=ap2a

I can only choose this as lunch option and only by typing it fully:
lunch aosp_xqde54-ap2a-eng

on15@51NO:~/android$ lunch aosp_xqde54-ap2a

Invalid lunch combo: aosp_xqde54-ap2a
Valid combos must be of the form <product>-<release>-<variant>
on15@51NO:~/android$ lunch aosp_xqde54-eng

Invalid lunch combo: aosp_xqde54-eng
Valid combos must be of the form <product>-<release>-<variant>
on15@51NO:~/android$ export aosp_pdx237-ap2a-eng
bash: export: »aosp_pdx237-ap2a-eng«: Ist kein gültiger Bezeichner
on15@51NO:~/android$ export aosp_pdx237-eng
bash: export: »aosp_pdx237-eng«: Ist kein gültiger Bezeichner
on15@51NO:~/android$ lunch aosp_xqde54-ap2a-eng

============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=14
PRODUCT_INCLUDE_TAGS=com.android.mainline mainline_module_prebuilt_nightly
TARGET_PRODUCT=aosp_xqde54
TARGET_BUILD_VARIANT=eng
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=generic
HOST_OS=linux
HOST_OS_EXTRA=Linux-5.15.0-113-generic-x86_64-Ubuntu-20.04.6-LTS
HOST_CROSS_OS=windows
BUILD_ID=AP2A.240605.024
OUT_DIR=out

**Comment by MarijnS95** [comment] 2024-07-15 15:38
Duplicate of https://github.com/sonyxperiadev/bug_tracker/issues/835 and https://github.com/sonyxperiadev/device-sony-common/issues/916 (both issues have a horrible, useless title, so you're forgiven).

**Comment by m113e55ml** [comment] 2024-07-15 15:44
cool

**Closed as completed** 2024-07-15 15:45 UTC
